### ISSUE TITLE
openApi Applying security

### ISSUE THREAD

**Issue by in0rdr** [nielsfalk/ktor-swagger#13]
Hello,

Today I learned about defining securitySchemes
(step 1 in https://swagger.io/docs/specification/authentication/):

```
openApi = OpenApi().apply {
            ...
            components.securitySchemes["BearerAuth"] = mapOf(
                        "type" to "http",
                        "scheme" to "bearer"
            )
            // paths["/corporations"]["security"] = Operation.create(...)
            ...
}
```

How can I apply security (step 2) to a path (e.g. "/corporations")?

Thanks

**Comment by nielsfalk** [comment]
Hi in0rdr,
currently you can't, but feel free to contribute with a pull request.
regards Niels
