### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JLLeitschuh** [nielsfalk/ktor-swagger#2]
I'd love to use this at my company, however, to do so you'd need to license this under a permissive license (something like Apache, BDS, or MIT). Would you be so kind as to add a License.txt file to this repository?

**Comment by nielsfalk** [comment]
I'll choose the same license as KTOR itself. It might be merged into Ktor some day. But currently I'm not sure if it is still compatible with the latest version.

**Comment by JLLeitschuh** [comment]
Thank you! I'll look into your code and try to gain some inspiration for the work I'm doing. 😄
