### ISSUE TITLE
The heroku link from the `README.md` is dead

### ISSUE THREAD

**Issue by holgerbrandl** [nielsfalk/ktor-swagger#21]

**Comment by JLLeitschuh** [comment]
@nielsfalk Do you have any time to fix this?

**Comment by nielsfalk** [comment]
Ok i fixed some [things](https://github.com/nielsfalk/ktor-swagger/commit/85f4970dd581984b2b948628204de46b31d21f58), but we need to do something like 
```
task copyToLib(type: Copy) {
    into "$buildDir/lib"
    from(configurations.compile)
}

stage.dependsOn(copyToLib)
```
in the ktor-sample-swagger.gradle.kts. But I have no idea how to do that in kotlin gradle dsl
@JLLeitschuh Can you help me there?

You can try the deployment local:
- install Heroku cli
- ./gradlew stage
- heroku local web

**Comment by JLLeitschuh** [comment]
Resolved! Thanks for the report!
