### ISSUE TITLE
Is it possible somehow to add static openApi.json file ?

### ISSUE THREAD

**Issue by artem-bakuta** [nielsfalk/ktor-swagger#48]
I have generated in swagger web-site openapi.json and openapi.yaml is it possible not to generate schemas from code and to replace it with static path to this files ??

**Comment by JLLeitschuh** [comment]
I mean, you can do that with base Ktor. If you want to do that, I don't know why you'd use this library.

**Comment by artem-bakuta** [comment]
> I mean, you can do that with base Ktor. If you want to do that, I don't know why you'd use this library.

sorry, any example to that ?

**Comment by JLLeitschuh** [comment]
Look at serving static content in the Ktor documentation.
On top of that, there's also a webjars module for Ktor if you want to use the Swagger UI in your project.

**Comment by artem-bakuta** [comment]
Great man, thank u !!!
